spring:
  profiles: 
   active: dev

---

spring:
  profiles: dev

startRoutee: timer:HELLO how are you?period=10s
fromRoute: file:input/data?delete=true&readLock=none
toRoute1: file:data/output

---

spring:
  profiles: stage

startRoutee: timer:hello how are you?period=10s
fromRoute: file:input/data?delete=true&readLock=none
toRoute1: file:data/output

---

spring:
  profiles: prod

startRoutee: timer:hello how are you?period=10s
fromRoute: file:input/data?delete=true&readLock=none
toRoute1: file:data/output

---
